stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_CONTAINER_NAME: morata
  DOCKER_IMAGE: morata
  DOCKER_TAG: latest

# Use Docker image with Docker-in-Docker (DinD) support
image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  only:
    - develop
  script:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
    - docker stop $DOCKER_CONTAINER_NAME || true
    - docker rm $DOCKER_CONTAINER_NAME || true
    - docker run -d -p 5000:5000 --name $DOCKER_CONTAINER_NAME $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
